name: Terraform Destroy

#on:
#  push:
#    branches:
#      - main  # Trigger on pushes to the main branch

on: workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
    # run in the correct directory - infrastructure/github-actions
    defaults:
      run:
        working-directory: ./infrastructure/github-actions

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: il-central-1

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region il-central-1 --name main-cluster

    - name: Delete kubernetes ingress
      working-directory: ./k8s
      run: kubectl delete -f eks-sample-ingress.yaml

    - name: Delete kubernetes deployment and service
      working-directory: ./k8s
      run: kubectl delete -f eks-sample-deployment.yaml

    - name: Helm Uninstall nginx-ingress
      run: helm uninstall nginx-ingress --namespace eks-sample-app

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
