name: Terraform Destroy

#on:
#  push:
#    branches:
#      - main  # Trigger on pushes to the main branch

on: workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
    # run in the correct directory - infrastructure/github-actions
    defaults:
      run:
        working-directory: ./infrastructure/github-actions

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.2

    # Step 3: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: il-central-1

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 5: Run terraform destroy
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
